#
# Sources description
#

airports:
    local     : true
    source    : Airports/Geonames/airports_geonames_only_clean.csv
    key_col   : iata_code
    delimiter : ^
    headers   :
        - iata_code
        - name
        - city_code
        - country_code
        - country_name
        - lat
        - lng


airports_csv:
    local     : true
    source    : Airports/AirportsDotCsv/ORI_Simple_Airports_Database_Table.csv
    key_col   : iata_code
    delimiter : ^
    headers   :
        - iata_code
        - ref_name
        - ref_name_2
        - name
        - city_code
        - is_an_airport
        - state_code
        - country_code
        - region_code       # REL_REGION_CODE in Amadeus RFD: AFRICCARIBEUROPPACIFSAMER...
        - pricing_zone      # REL_CONTINENT_CODE in Amadeus RFD: ITC1 ITC2 ITC3
        - time_zone_group   # REL_TIME_ZONE_GRP
        - lng
        - lat
        -                   # numeric code? -> converted to None => not loaded
        - is_commercial
        - location_type     # C city A airport H heliport O train station R rail


countries:
    local     : true
    source    : Countries/countryInfo.txt
    key_col   : code
    delimiter : "\t"
    headers   :
        - code
        - iso_alpha3
        - iso_numeric
        - fips_code
        - name
        - capital
        - area_in_sq_km
        - population
        - continent
        - tld
        - currency_code
        - currency_name
        - phone
        - postal_code_format
        - postal_code_regex
        - languages
        - geoname_id
        - neighbors


continents:
    local     : true
    source    : Continents/continentCodes.txt
    key_col   : code
    delimiter : "\t"
    headers   :
        - code
        - name
        - geoname_id


stations:
    local     : true
    source    : TrainStations/DataGouvFr/RFF/RFF_gares.ids.gm.man.red.csv
    key_col   : code
    delimiter : ^
    headers   :
        - code
        - lines
        - name
        - info
        - lat
        - lng


stations_nls:
    local     : true
    source    : TrainStations/NLS/NLS_CODES_RefDataSNCF.csv
    key_col   : nls_code
    delimiter : ','
    headers   :
        - uic_code
        - name
        - nls_code
        - physical


stations_uic:
    local     : true
    source    : TrainStations/UIC/sncfExtract_v1.0.csv
    key_col   : uic_code
    delimiter : ','
    headers   :
        - uic_code
        - name
        - lat
        - lng


languages:
    local     : true
    source    : Languages/iso-languagecodes.txt
    key_col   : code
    delimiter : "\t"
    headers   :
        - code
        - code_iso_2
        - code_iso_1
        - name


timezones:
    local     : true
    source    : TimeZones/timeZones.txt
    key_col   : code
    delimiter : "\t"
    headers   :
        - code
        - gmt_offset
        - dst_offset
        - raw_offset


cities:
    local     : true
    source    : Cities/cities15000.txt
    key_col   : code
    delimiter : "\t"
    headers   :
        - code
        - name
        - asciiname
        - alternatenames
        - lat
        - lng
        - fclass
        - fcode
        - country_code
        - cc2
        - admin1
        - admin2
        - admin3
        - admin4
        - population
        - elevation
        - dem
        - timezone
        - modification


ori_por:
    local     : true
    source    : Por/Ori/ori_por_public.csv
    key_col   : iata_code
    delimiter : ^
    headers   : &ori_por_headers
        - iata_code
        - icao_code
        - faa_code
        - is_geonames
        - geoname_id
        - valid_id
        - name
        - asciiname
        - lat           # is latitude  in ori_por headers
        - lng           # is longitude in ori_por headers
        - fclass
        - fcode
        - page_rank
        - date_from
        - date_until
        - comment
        - country_code
        - cc2
        - country_name
        - adm1_code
        - adm1_name_utf
        - adm1_name_ascii
        - adm2_code
        - adm2_name_utf
        - adm2_name_ascii
        - adm3_code
        - adm4_code
        - population
        - elevation
        - gtopo30
        - timezone
        - gmt_offset
        - dst_offset
        - raw_offset
        - moddate
        - is_airport
        - is_commercial
        - city_code
        - city_name_utf
        - city_name_ascii
        - state_code
        - region_code
        - location_type
        - wiki_link
        - alt_name_section


ori_por_multi:
    local     : true
    source    : Por/Ori/ori_por_public.csv
    key_col   : [iata_code, location_type]
    delimiter : ^
    headers   : *ori_por_headers


ori_por_non_iata:
    local     : true
    source    : Por/Ori/ori_por_non_iata.csv
    key_col   : iata_code
    delimiter : ^
    headers   : &short_ori_por_headers
        - iata_code
        - icao_code
        - faa_code
        - is_geonames
        - geoname_id
        - valid_id
        - name
        - asciiname
        - lat           # is latitude  in ori_por headers
        - lng           # is longitude in ori_por headers
        - fclass
        - fcode
        - page_rank
        - date_from
        - date_until
        - comment

