#
# Sources description
#

airports:
    source    : Airports/GeoNames/airports_geonames_only_clean.csv
    indexes   : iata_code
    delimiter : ^
    headers   :
        - iata_code
        - name
        - city_code
        - country_code
        - country_name
        - lat
        - lng


airports_csv:
    source    : Airports/AirportsDotCsv/ORI_Simple_Airports_Database_Table.csv
    indexes   : iata_code
    delimiter : ^
    headers   :
        - iata_code
        - ref_name
        - ref_name_2
        - name
        - city_code
        - is_an_airport
        - state_code
        - country_code
        - region_code       # REL_REGION_CODE in Amadeus RFD: AFRICCARIBEUROPPACIFSAMER...
        - pricing_zone      # REL_CONTINENT_CODE in Amadeus RFD: ITC1 ITC2 ITC3
        - time_zone_group   # REL_TIME_ZONE_GRP
        - lng
        - lat
        -                   # numeric code? -> converted to None => not loaded
        - is_commercial
        - location_type     # C city A airport H heliport O train station R rail


countries:
    source    : Countries/countryInfo.txt
    indexes   : code
    delimiter : "\t"
    subdelimiters :
        languages : ','
        neighbors : ','
    headers   :
        - code
        - iso_alpha3
        - iso_numeric
        - fips_code
        - name
        - capital
        - area_in_sq_km
        - population
        - continent
        - tld
        - currency_code
        - currency_name
        - phone
        - postal_code_format
        - postal_code_regex
        - languages
        - geoname_id
        - neighbors


capitals:
    source    : Countries/capitals.csv
    indexes   : country_code
    delimiter : ^
    headers   :
        - country_code
        - capital_name
        - country_name
        - area_in_sq_km
        - population
        - lat
        - lng


continents:
    source    : Continents/continentCodes.txt
    indexes   : code
    delimiter : "\t"
    headers   :
        - code
        - name
        - geoname_id


stations:
    source    : TrainStations/DataGouvFr/RFF_gares.ids.gm.man.red.csv
    indexes   : code
    delimiter : ^
    subdelimiters :
        lines: ','
    headers   :
        - code
        - lines
        - name
        - info
        - lat
        - lng


stations_nls:
    source    : TrainStations/NLS/NLS_CODES_RefDataSNCF.csv
    indexes   : nls_code
    delimiter : ','
    headers   :
        - uic_code
        - name
        - nls_code
        - physical


stations_uic:
    source    : TrainStations/UIC/sncfExtract_v1.0.csv
    indexes   : uic_code
    delimiter : ','
    headers   :
        - uic_code
        - name
        - lat
        - lng


languages:
    source    : Languages/iso-languagecodes.txt
    indexes   : code
    delimiter : "\t"
    headers   :
        - code
        - code_iso_2
        - code_iso_1
        - name


timezones:
    source    : TimeZones/timeZones.txt
    indexes   : code
    delimiter : "\t"
    headers   :
        - country_code
        - code
        - gmt_offset
        - dst_offset
        - raw_offset


cities:
    source    : Cities/cities15000.txt
    indexes   : code
    delimiter : "\t"
    subdelimiters :
        alternatenames : ','
    headers   :
        - code
        - name
        - asciiname
        - alternatenames
        - lat
        - lng
        - fclass
        - fcode
        - country_code
        - cc2
        - admin1
        - admin2
        - admin3
        - admin4
        - population
        - elevation
        - dem
        - timezone
        - modification


ori_por:
    source        : Por/Ori/ori_por_public.csv
    indexes       : iata_code
    limit         : # put a number to load only the first lines
    discard_dups  : false # This is the default behavior anyway
    delimiter     : ^
    subdelimiters : &ori_por_subdel
        # Here you may put '' to
        # split every char 'AB' -> ['A', 'B']
        #location_type    : ''
        alt_name_section : ['=', '|']
    headers : &ori_por_headers
        - iata_code
        - icao_code
        - faa_code
        - is_geonames
        - geoname_id
        - valid_id
        - name
        - asciiname
        - lat           # is latitude  in ori_por headers
        - lng           # is longitude in ori_por headers
        - fclass
        - fcode
        - page_rank
        - date_from
        - date_until
        - comment
        - country_code
        - cc2
        - country_name
        - adm1_code
        - adm1_name_utf
        - adm1_name_ascii
        - adm2_code
        - adm2_name_utf
        - adm2_name_ascii
        - adm3_code
        - adm4_code
        - population
        - elevation
        - gtopo30
        - timezone
        - gmt_offset
        - dst_offset
        - raw_offset
        - moddate
        - is_airport
        - is_commercial
        - city_code
        - city_name_utf
        - city_name_ascii
        - state_code
        - region_code
        - location_type
        - wiki_link
        - alt_name_section


ori_por_multi:
    source        : Por/Ori/ori_por_public.csv
    indexes       : [iata_code, location_type]
    delimiter     : ^
    subdelimiters : *ori_por_subdel
    headers       : *ori_por_headers


ori_por_non_iata:
    source    : Por/Ori/ori_por_non_iata.csv
    indexes   : iata_code
    delimiter : ^
    headers   : &short_ori_por_headers
        - iata_code
        - icao_code
        - faa_code
        - is_geonames
        - geoname_id
        - valid_id
        - name
        - asciiname
        - lat           # is latitude  in ori_por headers
        - lng           # is longitude in ori_por headers
        - fclass
        - fcode
        - page_rank
        - date_from
        - date_until
        - comment


currencies:
    source    : Currencies/wiki_source_ISO_4217.csv
    indexes   : currency_code
    delimiter : ;
    subdelimiters :
        countries : ','
    headers   :
        - currency_code
        - numeric_code
        - digits_number
        - currency_name
        - countries


airlines:
    source    : Airlines/ori_airlines.csv
    indexes   : unified_code
    delimiter : ^
    headers   :
        - unified_code
        - 3char_code
        - 2char_code
        - num_code
        - name
        - name2
        - alliance_code
        - alliance_status


cabins:
    source    : Cabins/cabins.csv
    indexes   : code
    delimiter : ^
    headers   :
        - code
        - name


regions:
    source    : Regions/regions.csv
    indexes   : code
    delimiter : ;
    headers   :
        - code
        - name


locales:
    source    : Locales/locales.csv
    indexes   : locale
    delimiter : ;
    headers   :
        - locale
        - title
        - language
        - territory
        - revision
        - date
        - codeset


location_types:
    source    : LocationTypes/location_types.csv
    indexes   : location_type
    delimiter : ^
    headers   :
        - location_type
        - name


feature_classes:
    source    : FeatureClasses/feature_classes.csv
    indexes   : fclass
    delimiter : ^
    headers   :
        - fclass
        - name


feature_codes:
    source    : FeatureCodes/featureCodes_en.txt
    indexes   : fcode
    delimiter : "\t"
    headers   :
        - fclass
        - fcode
        - name
        - description


geonames_FR:
    source    : Por/GeoNames/FR.txt
    indexes   : geoname_id
    delimiter : "\t"
    subdelimiters :
        alternatenames : ','
    headers   : *geonames_headers


geonames_MC:
    source    : Por/GeoNames/MC.txt
    indexes   : geoname_id
    delimiter : "\t"
    subdelimiters :
        alternatenames : ','
    headers   : *geonames_headers


postal_codes_FR:
    source    : PostalCodes/GeoNames/FR.txt
    indexes   : *postal_codes_ind
    delimiter : "\t"
    headers   : *postal_codes_headers


postal_codes_MC:
    source    : PostalCodes/GeoNames/MC.txt
    indexes   : *postal_codes_ind
    delimiter : "\t"
    headers   : *postal_codes_headers


office_ids:
    source    : Office_IDs/OfficeIDs_and_names.csv
    indexes   : office_id
    delimiter : ","
    #quotechar : '"' # that is the default
    headers   :
        - office_id
        - name

