language: python
python:
  - "2.6"
  - "2.7"

notifications:
  email:
      - alexprengere@gmail.com

# command to install dependencies
install:
    - "python setup.py install"

# command to run tests
script: "python test/test_GeoBases.py -vv"
