language: python
python:
  - "3.2"
  - "3.3"

notifications:
  email:
      - alexprengere@gmail.com

matrix:
  allow_failures:
    - python: "3.3"

# command to install dependencies
install:
    - "python setup.py install"

# command to run tests
script: "python test/test_GeoBases.py -vv"
