language: python
python:
  - "2.6"

notifications:
  email:
      - alexprengere@gmail.com

# command to install dependencies
install: "python setup.py install --user"

# command to run tests
script: "python test/test_GeoBases.py -v"
