language: python
python:
  - "3.2"
  #- "3.3"

notifications:
  email:
      - alexprengere@gmail.com

# command to install dependencies
install:
    - "python setup.py install"

# command to run tests
script: "python test/test_GeoBases.py -vv"
